
export type TSCFlags = {
    excludeDirectories?: string[];
    excludeFiles?: string[];
    fallbackPolling?: 'fixedinterval' | 'priorityinterval' | 'dynamicpriority' | 'fixedchunksize';
    synchronousWatchDirectory?: boolean;
    watch?: boolean;
    watchDirectory?: 'usefsevents' | 'fixedpollinginterval' | 'dynamicprioritypolling' | 'fixedchunksizepolling';
    watchFile?: 'fixedpollinginterval' | 'prioritypollinginterval' | 'dynamicprioritypolling' | 'fixedchunksizepolling' | 'usefsevents' | 'usefseventsonparentdirectory';

    allowArbitraryExtensions?: boolean;
    allowImportingTsExtensions?: boolean;
    allowJs?: boolean;
    allowSyntheticDefaultImports?: boolean;
    allowUmdGlobalAccess?: boolean;
    allowUnreachableCode?: boolean;
    allowUnusedLabels?: boolean;
    alwaysStrict?: boolean;
    assumeChangesOnlyAffectDirectDependencies?: boolean;
    baseUrl?: string;
    charset?: string;
    checkJs?: boolean;
    composite?: boolean;
    customConditions?: string[];
    declaration?: boolean;
    declarationDir?: string;
    declarationMap?: boolean;
    diagnostics?: boolean;
    disableReferencedProjectLoad?: boolean;
    disableSizeLimit?: boolean;
    disableSolutionSearching?: boolean;
    disableSourceOfProjectReferenceRedirect?: boolean;
    downlevelIteration?: boolean;
    emitBOM?: boolean;
    emitDeclarationOnly?: boolean;
    emitDecoratorMetadata?: boolean;
    esModuleInterop?: boolean;
    exactOptionalPropertyTypes?: boolean;
    experimentalDecorators?: boolean;
    explainFiles?: boolean;
    extendedDiagnostics?: boolean;
    forceConsistentCasingInFileNames?: boolean;
    generateCpuProfile?: string;
    importHelpers?: boolean;
    importsNotUsedAsValues?: 'remove' | 'preserve' | 'error';
    incremental?: boolean;
    inlineSourceMap?: boolean;
    inlineSources?: boolean;
    isolatedModules?: boolean;
    jsx?: 'preserve' | 'react' | 'react-native' | 'react-jsx' | 'react-jsxdev';
    jsxFactory?: string;
    jsxFragmentFactory?: string;
    jsxImportSource?: string;
    keyofStringsOnly?: boolean;
    lib?: string[];
    listEmittedFiles?: boolean;
    listFiles?: boolean;
    mapRoot?: string;
    maxNodeModuleJsDepth?: number;
    module?: 'none' | 'commonjs' | 'amd' | 'umd' | 'system' | 'es6' | 'es2015' | 'es2020' | 'es2022' | 'esnext' | 'node16' | 'nodenext' | 'preserve';
    moduleDetection?: 'legacy' | 'auto' | 'force';
    moduleResolution?: 'classic' | 'node10' | 'node' | 'node16' | 'nodenext' | 'bundler';
    moduleSuffixes?: string[];
    newLine?: 'crlf' | 'lf';
    noEmit?: boolean;
    noEmitHelpers?: boolean;
    noEmitOnError?: boolean;
    noErrorTruncation?: boolean;
    noFallthroughCasesInSwitch?: boolean;
    noImplicitAny?: boolean;
    noImplicitOverride?: boolean;
    noImplicitReturns?: boolean;
    noImplicitThis?: boolean;
    noImplicitUseStrict?: boolean;
    noLib?: boolean;
    noPropertyAccessFromIndexSignature?: boolean;
    noResolve?: boolean;
    noStrictGenericChecks?: boolean;
    noUncheckedIndexedAccess?: boolean;
    noUnusedLocals?: boolean;
    noUnusedParameters?: boolean;
    out?: string;
    outDir?: string;
    outFile?: string;
    paths?: Record<string, string[]>;
    plugins?: Array<{ name: string;[option: string]: any; }>;
    preserveConstEnums?: boolean;
    preserveSymlinks?: boolean;
    preserveValueImports?: boolean;
    preserveWatchOutput?: boolean;
    pretty?: boolean;
    reactNamespace?: string;
    removeComments?: boolean;
    resolveJsonModule?: boolean;
    resolvePackageJsonExports?: boolean;
    resolvePackageJsonImports?: boolean;
    rootDir?: string;
    rootDirs?: string[];
    skipDefaultLibCheck?: boolean;
    skipLibCheck?: boolean;
    sourceMap?: boolean;
    sourceRoot?: string;
    strict?: boolean;
    strictBindCallApply?: boolean;
    strictFunctionTypes?: boolean;
    strictNullChecks?: boolean;
    strictPropertyInitialization?: boolean;
    stripInternal?: boolean;
    suppressExcessPropertyErrors?: boolean;
    suppressImplicitAnyIndexErrors?: boolean;
    target?: 'es3' | 'es5' | 'es6' | 'es2015' | 'es2016' | 'es2017' | 'es2018' | 'es2019' | 'es2020' | 'es2021' | 'es2022' | 'esnext';
    traceResolution?: boolean;
    tsBuildInfoFile?: string;
    typeRoots?: string[];
    types?: string[];
    useDefineForClassFields?: boolean;
    useUnknownInCatchVariables?: boolean;
    verbatimModuleSyntax?: boolean;
};
