npmConfig:
  scripts:
    start: "tsc && node ./dist"
  devDependencies:
    - "@types/express"
  dependencies:
    - "inversify"
    - "typeorm"
    - "inversify-express-utils"
    - "express"

tscConfig:
  experimentalDecorators: true
  emitDecoratorMetadata: true
