npmConfig:
  scripts:
    start: "webpack serve"
    build: "webpack"
  dependencies:
    - "react"
    - "react-dom"
    - "autoprefixer"
    - "postcss-loader"
    - "tailwindcss"
  devDependencies:
    - "@types/react"
    - "@types/react-dom"
    - "css-loader"
    - "html-webpack-plugin"
    - "mini-css-extract-plugin"
    - "ts-loader"
    - "webpack-cli"
    - "webpack"
    - "webpack-dev-server"

tscConfig:
  target: "es2016"
  skipLibCheck: true
  esModuleInterop: true
  forceConsistentCasingInFileNames: true
  noFallthroughCasesInSwitch: true
  module: "esnext"
  moduleResolution: "node"
  resolveJsonModule: true
  isolatedModules: true
  jsx: "react"

